### PR TITLE
Rebuild for python 3.13

### PR DESCRIPTION
**Pull request by tkelman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

needed for https://github.com/conda-forge/ruamel.yaml-feedstock/pull/196, but looks like the bot didn't trigger this yet because it's not solvable with the cython bound

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
This is now at the same point why the bot didn't open a PR. This package needs to be ported to Cython 3.x

**Comment by tkelman** [comment]
I was not expecting the simplest attempt of removing the upper bound to build without errors. Not familiar enough with cython-based packages' build process to guess whether that would function properly.

**Comment by xhochy** [comment]
Looks like it build successfully.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
