### PR TITLE
 Add test/downstreams for ruamel.yaml

### LINKED ISSUE #22: @conda-forge-admin, please rerender
### Additional comment:

Want to add downstream test for ruamel.yaml

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #22.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #22

### CODE REVIEW

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
Thanks for the merge Filipe!

**Comment by ocefpaf** [comment]
> Thanks for the merge Filipe!

Thank you for fixing this. I always forget about test/downstream.

**Comment by mbargull** [comment]
Who doesn't ;).

**Comment by mbargull** [comment]
I'll add `conda` to `test/downstreams` later (after we have a `conda>=22.12` build) so we have that  one covered, too.
(I don't think `test/downstreams` is transitive, i.e., whether a `ruamel.yaml.clib`->`ruamel.yaml`->`conda` test chain would be set off; but IDK, we'll see once we try it out).

**Pull request merged**
